
// File generated by bin2lvgl.py
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 1889_2_390

#ifndef _FACE_1889_2_390_H
#define _FACE_1889_2_390_H

#ifdef __cplusplus
extern "C"
{
#endif

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
    #include "lvgl.h"
    #include "lvgl_private.h"
#else
    #include "lvgl/lvgl.h"
    #include "lvgl/lvgl_private.h"
#endif

#include "helios_ui/helios_ui.h"
#include "helios_ui/custom/watchfaces/watchface_manager.h"

#ifndef ENABLE_FACE_1889_2_390
#define ENABLE_FACE_1889_2_390
#endif

#ifdef ENABLE_FACE_1889_2_390

LV_IMG_DECLARE(face_1889_2_390_dial_img_0_1370_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_2_56054_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_3_57970_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_4_59998_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_5_61992_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_6_64018_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_7_66168_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_8_68270_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_9_70294_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_10_72404_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_11_74388_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_12_85542_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_13_96484_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_14_107334_6);
LV_IMG_DECLARE(face_1889_2_390_dial_img_14_107334_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_14_107334_1);
LV_IMG_DECLARE(face_1889_2_390_dial_img_14_107334_2);
LV_IMG_DECLARE(face_1889_2_390_dial_img_14_107334_3);
LV_IMG_DECLARE(face_1889_2_390_dial_img_14_107334_4);
LV_IMG_DECLARE(face_1889_2_390_dial_img_14_107334_5);
LV_IMG_DECLARE(face_1889_2_390_dial_img_15_118736_6);
LV_IMG_DECLARE(face_1889_2_390_dial_img_15_118736_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_15_118736_1);
LV_IMG_DECLARE(face_1889_2_390_dial_img_15_118736_2);
LV_IMG_DECLARE(face_1889_2_390_dial_img_15_118736_3);
LV_IMG_DECLARE(face_1889_2_390_dial_img_15_118736_4);
LV_IMG_DECLARE(face_1889_2_390_dial_img_15_118736_5);
LV_IMG_DECLARE(face_1889_2_390_dial_img_16_133792_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_17_136770_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_18_138936_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_18_138936_1);
LV_IMG_DECLARE(face_1889_2_390_dial_img_18_138936_2);
LV_IMG_DECLARE(face_1889_2_390_dial_img_18_138936_3);
LV_IMG_DECLARE(face_1889_2_390_dial_img_18_138936_4);
LV_IMG_DECLARE(face_1889_2_390_dial_img_18_138936_5);
LV_IMG_DECLARE(face_1889_2_390_dial_img_18_138936_6);
LV_IMG_DECLARE(face_1889_2_390_dial_img_18_138936_7);
LV_IMG_DECLARE(face_1889_2_390_dial_img_18_138936_8);
LV_IMG_DECLARE(face_1889_2_390_dial_img_18_138936_9);
LV_IMG_DECLARE(face_1889_2_390_dial_img_22_150310_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_22_150310_1);
LV_IMG_DECLARE(face_1889_2_390_dial_img_22_150310_2);
LV_IMG_DECLARE(face_1889_2_390_dial_img_22_150310_3);
LV_IMG_DECLARE(face_1889_2_390_dial_img_22_150310_4);
LV_IMG_DECLARE(face_1889_2_390_dial_img_22_150310_5);
LV_IMG_DECLARE(face_1889_2_390_dial_img_22_150310_6);
LV_IMG_DECLARE(face_1889_2_390_dial_img_22_150310_7);
LV_IMG_DECLARE(face_1889_2_390_dial_img_22_150310_8);
LV_IMG_DECLARE(face_1889_2_390_dial_img_22_150310_9);
LV_IMG_DECLARE(face_1889_2_390_dial_img_26_155854_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_30_0_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_35_156216_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_36_157054_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_38_157817_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_39_159058_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_39_159058_1);
LV_IMG_DECLARE(face_1889_2_390_dial_img_39_159058_2);
LV_IMG_DECLARE(face_1889_2_390_dial_img_39_159058_3);
LV_IMG_DECLARE(face_1889_2_390_dial_img_39_159058_4);
LV_IMG_DECLARE(face_1889_2_390_dial_img_39_159058_5);
LV_IMG_DECLARE(face_1889_2_390_dial_img_39_159058_6);
LV_IMG_DECLARE(face_1889_2_390_dial_img_39_159058_7);
LV_IMG_DECLARE(face_1889_2_390_dial_img_39_159058_8);
LV_IMG_DECLARE(face_1889_2_390_dial_img_39_159058_9);
LV_IMG_DECLARE(face_1889_2_390_dial_img_preview_0);
LV_IMG_DECLARE(face_1889_2_390_dial_img_preview_0);


#endif

lv_obj_t *init_face_1889_2_390(lv_obj_t *parent);
    

#ifdef __cplusplus
}
#endif

#endif
