
// File generated by bin2lvgl.py
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 1889_2_390

#include "1889_2_390.h"

#ifdef ENABLE_FACE_1889_2_390

static const void *face_1889_2_390_dial_img_weather[] = {
	&face_1889_2_390_dial_img_2_56054_0,
	&face_1889_2_390_dial_img_3_57970_0,
	&face_1889_2_390_dial_img_4_59998_0,
	&face_1889_2_390_dial_img_5_61992_0,
	&face_1889_2_390_dial_img_6_64018_0,
	&face_1889_2_390_dial_img_7_66168_0,
	&face_1889_2_390_dial_img_8_68270_0,
	&face_1889_2_390_dial_img_9_70294_0,
	&face_1889_2_390_dial_img_10_72404_0,
};
static const void *face_1889_2_390_dial_img_14_107334_group[] = {
	&face_1889_2_390_dial_img_14_107334_6,
	&face_1889_2_390_dial_img_14_107334_0,
	&face_1889_2_390_dial_img_14_107334_1,
	&face_1889_2_390_dial_img_14_107334_2,
	&face_1889_2_390_dial_img_14_107334_3,
	&face_1889_2_390_dial_img_14_107334_4,
	&face_1889_2_390_dial_img_14_107334_5,
};
static const void *face_1889_2_390_dial_img_15_118736_group[] = {
	&face_1889_2_390_dial_img_15_118736_6,
	&face_1889_2_390_dial_img_15_118736_0,
	&face_1889_2_390_dial_img_15_118736_1,
	&face_1889_2_390_dial_img_15_118736_2,
	&face_1889_2_390_dial_img_15_118736_3,
	&face_1889_2_390_dial_img_15_118736_4,
	&face_1889_2_390_dial_img_15_118736_5,
};
static const void *face_1889_2_390_dial_img_18_138936_group[] = {
	&face_1889_2_390_dial_img_18_138936_0,
	&face_1889_2_390_dial_img_18_138936_1,
	&face_1889_2_390_dial_img_18_138936_2,
	&face_1889_2_390_dial_img_18_138936_3,
	&face_1889_2_390_dial_img_18_138936_4,
	&face_1889_2_390_dial_img_18_138936_5,
	&face_1889_2_390_dial_img_18_138936_6,
	&face_1889_2_390_dial_img_18_138936_7,
	&face_1889_2_390_dial_img_18_138936_8,
	&face_1889_2_390_dial_img_18_138936_9,
};
static const void *face_1889_2_390_dial_img_22_150310_group[] = {
	&face_1889_2_390_dial_img_22_150310_0,
	&face_1889_2_390_dial_img_22_150310_1,
	&face_1889_2_390_dial_img_22_150310_2,
	&face_1889_2_390_dial_img_22_150310_3,
	&face_1889_2_390_dial_img_22_150310_4,
	&face_1889_2_390_dial_img_22_150310_5,
	&face_1889_2_390_dial_img_22_150310_6,
	&face_1889_2_390_dial_img_22_150310_7,
	&face_1889_2_390_dial_img_22_150310_8,
	&face_1889_2_390_dial_img_22_150310_9,
};
static const void *face_1889_2_390_dial_img_39_159058_group[] = {
	&face_1889_2_390_dial_img_39_159058_0,
	&face_1889_2_390_dial_img_39_159058_1,
	&face_1889_2_390_dial_img_39_159058_2,
	&face_1889_2_390_dial_img_39_159058_3,
	&face_1889_2_390_dial_img_39_159058_4,
	&face_1889_2_390_dial_img_39_159058_5,
	&face_1889_2_390_dial_img_39_159058_6,
	&face_1889_2_390_dial_img_39_159058_7,
	&face_1889_2_390_dial_img_39_159058_8,
	&face_1889_2_390_dial_img_39_159058_9,
};




HELIOS_REGISTER_WATCHFACE(
    "1889 2 390",
    "1889_2_390",
    init_face_1889_2_390,
    &face_1889_2_390_dial_img_preview_0
);

#endif

lv_obj_t *init_face_1889_2_390(lv_obj_t *parent){
    lv_obj_t *face_1889_2_390 = lv_obj_create(parent);
#ifdef ENABLE_FACE_1889_2_390
    
    lv_obj_remove_style_all(face_1889_2_390);
    lv_obj_set_size(face_1889_2_390, lv_pct(100),lv_pct(100));
    lv_obj_set_flag(face_1889_2_390, LV_OBJ_FLAG_SCROLLABLE, false);
    lv_obj_set_flag(face_1889_2_390, LV_OBJ_FLAG_CLICKABLE, false);

    
    lv_obj_t *face_1889_2_390_0_1370 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_0_1370, &face_1889_2_390_dial_img_0_1370_0);
    lv_obj_set_width(face_1889_2_390_0_1370, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_0_1370, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_0_1370, 8);
    lv_obj_set_y(face_1889_2_390_0_1370, 195);

    lv_obj_t *face_1889_2_390_2_56054 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_2_56054, 0);
    wf_item_set_image_array(face_1889_2_390_2_56054, face_1889_2_390_dial_img_weather, 8);
    wf_item_bind_subject(face_1889_2_390_2_56054, &sb_weather_code);
    lv_obj_set_x(face_1889_2_390_2_56054, 245);
    lv_obj_set_y(face_1889_2_390_2_56054, 143);

    lv_obj_t *face_1889_2_390_11_74388 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_11_74388, &face_1889_2_390_dial_img_11_74388_0);
    lv_obj_set_width(face_1889_2_390_11_74388, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_11_74388, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_11_74388, 19);
    lv_obj_set_y(face_1889_2_390_11_74388, 354);

    lv_obj_t *face_1889_2_390_12_85542 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_12_85542, &face_1889_2_390_dial_img_12_85542_0);
    lv_obj_set_width(face_1889_2_390_12_85542, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_12_85542, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_12_85542, 143);
    lv_obj_set_y(face_1889_2_390_12_85542, 354);

    lv_obj_t *face_1889_2_390_13_96484 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_13_96484, &face_1889_2_390_dial_img_13_96484_0);
    lv_obj_set_width(face_1889_2_390_13_96484, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_13_96484, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_13_96484, 266);
    lv_obj_set_y(face_1889_2_390_13_96484, 354);

    lv_obj_t *face_1889_2_390_15_118736 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_15_118736, 0);
    wf_item_set_image_array(face_1889_2_390_15_118736, face_1889_2_390_dial_img_15_118736_group, 7);
    wf_item_bind_subject(face_1889_2_390_15_118736, &sb_time_weekday);
    lv_obj_set_x(face_1889_2_390_15_118736, 131);
    lv_obj_set_y(face_1889_2_390_15_118736, 146);

    lv_obj_t *face_1889_2_390_17_136770 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_17_136770, &face_1889_2_390_dial_img_17_136770_0);
    lv_obj_set_width(face_1889_2_390_17_136770, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_17_136770, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_17_136770, 43);
    lv_obj_set_y(face_1889_2_390_17_136770, 225);

    lv_obj_t *face_1889_2_390_18_138936 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_18_138936, 0);
    wf_item_set_image_array(face_1889_2_390_18_138936, face_1889_2_390_dial_img_18_138936_group, 10);
    wf_item_bind_subject(face_1889_2_390_18_138936, &sb_activity_kcal);
    lv_obj_set_x(face_1889_2_390_18_138936, 128);
    lv_obj_set_y(face_1889_2_390_18_138936, 269);

    lv_obj_t *face_1889_2_390_19_138936 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_19_138936, 1);
    wf_item_set_image_array(face_1889_2_390_19_138936, face_1889_2_390_dial_img_18_138936_group, 10);
    wf_item_bind_subject(face_1889_2_390_19_138936, &sb_activity_kcal);
    lv_obj_set_x(face_1889_2_390_19_138936, 99);
    lv_obj_set_y(face_1889_2_390_19_138936, 269);

    lv_obj_t *face_1889_2_390_20_138936 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_20_138936, 2);
    wf_item_set_image_array(face_1889_2_390_20_138936, face_1889_2_390_dial_img_18_138936_group, 10);
    wf_item_bind_subject(face_1889_2_390_20_138936, &sb_activity_kcal);
    lv_obj_set_x(face_1889_2_390_20_138936, 69);
    lv_obj_set_y(face_1889_2_390_20_138936, 269);

    lv_obj_t *face_1889_2_390_21_138936 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_21_138936, 3);
    wf_item_set_image_array(face_1889_2_390_21_138936, face_1889_2_390_dial_img_18_138936_group, 10);
    wf_item_bind_subject(face_1889_2_390_21_138936, &sb_activity_kcal);
    lv_obj_set_x(face_1889_2_390_21_138936, 40);
    lv_obj_set_y(face_1889_2_390_21_138936, 269);

    lv_obj_t *face_1889_2_390_22_150310 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_22_150310, 0);
    wf_item_set_image_array(face_1889_2_390_22_150310, face_1889_2_390_dial_img_22_150310_group, 10);
    wf_item_bind_subject(face_1889_2_390_22_150310, &sb_time_month);
    lv_obj_set_x(face_1889_2_390_22_150310, 45);
    lv_obj_set_y(face_1889_2_390_22_150310, 146);

    lv_obj_t *face_1889_2_390_23_150310 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_23_150310, 1);
    wf_item_set_image_array(face_1889_2_390_23_150310, face_1889_2_390_dial_img_22_150310_group, 10);
    wf_item_bind_subject(face_1889_2_390_23_150310, &sb_time_month);
    lv_obj_set_x(face_1889_2_390_23_150310, 24);
    lv_obj_set_y(face_1889_2_390_23_150310, 146);

    lv_obj_t *face_1889_2_390_24_150310 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_24_150310, 0);
    wf_item_set_image_array(face_1889_2_390_24_150310, face_1889_2_390_dial_img_22_150310_group, 10);
    wf_item_bind_subject(face_1889_2_390_24_150310, &sb_time_day);
    lv_obj_set_x(face_1889_2_390_24_150310, 100);
    lv_obj_set_y(face_1889_2_390_24_150310, 146);

    lv_obj_t *face_1889_2_390_25_150310 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_25_150310, 1);
    wf_item_set_image_array(face_1889_2_390_25_150310, face_1889_2_390_dial_img_22_150310_group, 10);
    wf_item_bind_subject(face_1889_2_390_25_150310, &sb_time_day);
    lv_obj_set_x(face_1889_2_390_25_150310, 79);
    lv_obj_set_y(face_1889_2_390_25_150310, 146);

    lv_obj_t *face_1889_2_390_26_155854 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_26_155854, &face_1889_2_390_dial_img_26_155854_0);
    lv_obj_set_width(face_1889_2_390_26_155854, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_26_155854, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_26_155854, 66);
    lv_obj_set_y(face_1889_2_390_26_155854, 144);

    lv_obj_t *face_1889_2_390_27_150310 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_27_150310, 0);
    wf_item_set_image_array(face_1889_2_390_27_150310, face_1889_2_390_dial_img_22_150310_group, 10);
    wf_item_bind_subject(face_1889_2_390_27_150310, &sb_health_bpm);
    lv_obj_set_x(face_1889_2_390_27_150310, 326);
    lv_obj_set_y(face_1889_2_390_27_150310, 419);

    lv_obj_t *face_1889_2_390_28_150310 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_28_150310, 1);
    wf_item_set_image_array(face_1889_2_390_28_150310, face_1889_2_390_dial_img_22_150310_group, 10);
    wf_item_bind_subject(face_1889_2_390_28_150310, &sb_health_bpm);
    lv_obj_set_x(face_1889_2_390_28_150310, 307);
    lv_obj_set_y(face_1889_2_390_28_150310, 419);

    lv_obj_t *face_1889_2_390_29_150310 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_29_150310, 2);
    wf_item_set_image_array(face_1889_2_390_29_150310, face_1889_2_390_dial_img_22_150310_group, 10);
    wf_item_bind_subject(face_1889_2_390_29_150310, &sb_health_bpm);
    lv_obj_set_x(face_1889_2_390_29_150310, 287);
    lv_obj_set_y(face_1889_2_390_29_150310, 419);

    lv_obj_t *face_1889_2_390_30_0 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_30_0, &face_1889_2_390_dial_img_30_0_0);
    lv_obj_set_width(face_1889_2_390_30_0, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_30_0, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_30_0, 331);
    lv_obj_set_y(face_1889_2_390_30_0, 159);

    lv_obj_t *face_1889_2_390_31_0 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_31_0, &face_1889_2_390_dial_img_30_0_0);
    lv_obj_set_width(face_1889_2_390_31_0, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_31_0, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_31_0, 312);
    lv_obj_set_y(face_1889_2_390_31_0, 159);

    lv_obj_t *face_1889_2_390_32_150310 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_32_150310, &face_1889_2_390_dial_img_22_150310_0);
    lv_obj_set_width(face_1889_2_390_32_150310, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_32_150310, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_32_150310, 331);
    lv_obj_set_y(face_1889_2_390_32_150310, 147);

    lv_obj_t *face_1889_2_390_33_150310 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_33_150310, &face_1889_2_390_dial_img_22_150310_0);
    lv_obj_set_width(face_1889_2_390_33_150310, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_33_150310, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_33_150310, 312);
    lv_obj_set_y(face_1889_2_390_33_150310, 147);

    lv_obj_t *face_1889_2_390_34_150310 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_34_150310, &face_1889_2_390_dial_img_22_150310_0);
    lv_obj_set_width(face_1889_2_390_34_150310, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_34_150310, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_34_150310, 294);
    lv_obj_set_y(face_1889_2_390_34_150310, 147);

    lv_obj_t *face_1889_2_390_35_156216 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_35_156216, &face_1889_2_390_dial_img_35_156216_0);
    lv_obj_set_width(face_1889_2_390_35_156216, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_35_156216, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_35_156216, 352);
    lv_obj_set_y(face_1889_2_390_35_156216, 147);

    lv_obj_t *face_1889_2_390_36_157054 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_36_157054, &face_1889_2_390_dial_img_36_157054_0);
    lv_obj_set_width(face_1889_2_390_36_157054, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_36_157054, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_36_157054, 352);
    lv_obj_set_y(face_1889_2_390_36_157054, 147);

    lv_obj_t *face_1889_2_390_37_0 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_37_0, &face_1889_2_390_dial_img_30_0_0);
    lv_obj_set_width(face_1889_2_390_37_0, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_37_0, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_37_0, 294);
    lv_obj_set_y(face_1889_2_390_37_0, 159);

    lv_obj_t *face_1889_2_390_38_157817 = lv_img_create(face_1889_2_390);
    lv_img_set_src(face_1889_2_390_38_157817, &face_1889_2_390_dial_img_38_157817_0);
    lv_obj_set_width(face_1889_2_390_38_157817, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1889_2_390_38_157817, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1889_2_390_38_157817, 180);
    lv_obj_set_y(face_1889_2_390_38_157817, 45);

    lv_obj_t *face_1889_2_390_39_159058 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_39_159058, 0);
    wf_item_set_image_array(face_1889_2_390_39_159058, face_1889_2_390_dial_img_39_159058_group, 10);
    wf_item_bind_subject(face_1889_2_390_39_159058, &sb_time_hour);
    lv_obj_set_x(face_1889_2_390_39_159058, 105);
    lv_obj_set_y(face_1889_2_390_39_159058, 27);

    lv_obj_t *face_1889_2_390_40_159058 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_40_159058, 1);
    wf_item_set_image_array(face_1889_2_390_40_159058, face_1889_2_390_dial_img_39_159058_group, 10);
    wf_item_bind_subject(face_1889_2_390_40_159058, &sb_time_hour);
    lv_obj_set_x(face_1889_2_390_40_159058, 30);
    lv_obj_set_y(face_1889_2_390_40_159058, 27);

    lv_obj_t *face_1889_2_390_41_159058 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_41_159058, 0);
    wf_item_set_image_array(face_1889_2_390_41_159058, face_1889_2_390_dial_img_39_159058_group, 10);
    wf_item_bind_subject(face_1889_2_390_41_159058, &sb_time_minute);
    lv_obj_set_x(face_1889_2_390_41_159058, 277);
    lv_obj_set_y(face_1889_2_390_41_159058, 27);

    lv_obj_t *face_1889_2_390_42_159058 = wf_item_create(face_1889_2_390);
    wf_item_set_place_value(face_1889_2_390_42_159058, 1);
    wf_item_set_image_array(face_1889_2_390_42_159058, face_1889_2_390_dial_img_39_159058_group, 10);
    wf_item_bind_subject(face_1889_2_390_42_159058, &sb_time_minute);
    lv_obj_set_x(face_1889_2_390_42_159058, 203);
    lv_obj_set_y(face_1889_2_390_42_159058, 27);


#endif
    return face_1889_2_390;
}

