
// File generated by bin2lvgl.py
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 228_390

#include "228_390.h"

#ifdef ENABLE_FACE_228_390

static const void *face_228_390_dial_img_1_183246_group[] = {
	&face_228_390_dial_img_1_183246_0,
	&face_228_390_dial_img_1_183246_1,
	&face_228_390_dial_img_1_183246_2,
	&face_228_390_dial_img_1_183246_3,
	&face_228_390_dial_img_1_183246_4,
	&face_228_390_dial_img_1_183246_5,
	&face_228_390_dial_img_1_183246_6,
	&face_228_390_dial_img_1_183246_7,
	&face_228_390_dial_img_1_183246_8,
	&face_228_390_dial_img_1_183246_9,
};
static const void *face_228_390_dial_img_3_186360_group[] = {
	&face_228_390_dial_img_3_186360_0,
	&face_228_390_dial_img_3_186360_1,
	&face_228_390_dial_img_3_186360_2,
	&face_228_390_dial_img_3_186360_3,
	&face_228_390_dial_img_3_186360_4,
	&face_228_390_dial_img_3_186360_5,
	&face_228_390_dial_img_3_186360_6,
	&face_228_390_dial_img_3_186360_7,
	&face_228_390_dial_img_3_186360_8,
	&face_228_390_dial_img_3_186360_9,
};
static const void *face_228_390_dial_img_7_228194_group[] = {
	&face_228_390_dial_img_7_228194_6,
	&face_228_390_dial_img_7_228194_0,
	&face_228_390_dial_img_7_228194_1,
	&face_228_390_dial_img_7_228194_2,
	&face_228_390_dial_img_7_228194_3,
	&face_228_390_dial_img_7_228194_4,
	&face_228_390_dial_img_7_228194_5,
};
static const void *face_228_390_dial_img_8_235158_group[] = {
	&face_228_390_dial_img_8_235158_6,
	&face_228_390_dial_img_8_235158_0,
	&face_228_390_dial_img_8_235158_1,
	&face_228_390_dial_img_8_235158_2,
	&face_228_390_dial_img_8_235158_3,
	&face_228_390_dial_img_8_235158_4,
	&face_228_390_dial_img_8_235158_5,
};




HELIOS_REGISTER_WATCHFACE(
    "228",
    "228_390",
    init_face_228_390,
    &face_228_390_dial_img_preview_0
);

#endif

lv_obj_t *init_face_228_390(lv_obj_t *parent){
    lv_obj_t *face_228_390 = lv_obj_create(parent);
#ifdef ENABLE_FACE_228_390
    
    lv_obj_remove_style_all(face_228_390);
    lv_obj_set_size(face_228_390, lv_pct(100),lv_pct(100));
    lv_obj_set_flag(face_228_390, LV_OBJ_FLAG_SCROLLABLE, false);
    lv_obj_set_flag(face_228_390, LV_OBJ_FLAG_CLICKABLE, false);

    
    lv_obj_t *face_228_390_0_692 = lv_img_create(face_228_390);
    lv_img_set_src(face_228_390_0_692, &face_228_390_dial_img_0_692_0);
    lv_obj_set_width(face_228_390_0_692, LV_SIZE_CONTENT);
    lv_obj_set_height(face_228_390_0_692, LV_SIZE_CONTENT);
    lv_obj_set_x(face_228_390_0_692, 0);
    lv_obj_set_y(face_228_390_0_692, 0);

    lv_obj_t *face_228_390_1_183246 = wf_item_create(face_228_390);
    wf_item_set_place_value(face_228_390_1_183246, 0);
    wf_item_set_image_array(face_228_390_1_183246, face_228_390_dial_img_1_183246_group, 10);
    wf_item_bind_subject(face_228_390_1_183246, &sb_time_day);
    lv_obj_set_x(face_228_390_1_183246, 115);
    lv_obj_set_y(face_228_390_1_183246, 277);

    lv_obj_t *face_228_390_2_183246 = wf_item_create(face_228_390);
    wf_item_set_place_value(face_228_390_2_183246, 1);
    wf_item_set_image_array(face_228_390_2_183246, face_228_390_dial_img_1_183246_group, 10);
    wf_item_bind_subject(face_228_390_2_183246, &sb_time_day);
    lv_obj_set_x(face_228_390_2_183246, 100);
    lv_obj_set_y(face_228_390_2_183246, 277);

    lv_obj_t *face_228_390_3_186360 = wf_item_create(face_228_390);
    wf_item_set_place_value(face_228_390_3_186360, 0);
    wf_item_set_image_array(face_228_390_3_186360, face_228_390_dial_img_3_186360_group, 10);
    wf_item_bind_subject(face_228_390_3_186360, &sb_time_hour);
    lv_obj_set_x(face_228_390_3_186360, 89);
    lv_obj_set_y(face_228_390_3_186360, 86);

    lv_obj_t *face_228_390_4_186360 = wf_item_create(face_228_390);
    wf_item_set_place_value(face_228_390_4_186360, 1);
    wf_item_set_image_array(face_228_390_4_186360, face_228_390_dial_img_3_186360_group, 10);
    wf_item_bind_subject(face_228_390_4_186360, &sb_time_hour);
    lv_obj_set_x(face_228_390_4_186360, 22);
    lv_obj_set_y(face_228_390_4_186360, 86);

    lv_obj_t *face_228_390_5_186360 = wf_item_create(face_228_390);
    wf_item_set_place_value(face_228_390_5_186360, 0);
    wf_item_set_image_array(face_228_390_5_186360, face_228_390_dial_img_3_186360_group, 10);
    wf_item_bind_subject(face_228_390_5_186360, &sb_time_minute);
    lv_obj_set_x(face_228_390_5_186360, 89);
    lv_obj_set_y(face_228_390_5_186360, 183);

    lv_obj_t *face_228_390_6_186360 = wf_item_create(face_228_390);
    wf_item_set_place_value(face_228_390_6_186360, 1);
    wf_item_set_image_array(face_228_390_6_186360, face_228_390_dial_img_3_186360_group, 10);
    wf_item_bind_subject(face_228_390_6_186360, &sb_time_minute);
    lv_obj_set_x(face_228_390_6_186360, 22);
    lv_obj_set_y(face_228_390_6_186360, 183);

    lv_obj_t *face_228_390_8_235158 = wf_item_create(face_228_390);
    wf_item_set_place_value(face_228_390_8_235158, 0);
    wf_item_set_image_array(face_228_390_8_235158, face_228_390_dial_img_8_235158_group, 7);
    wf_item_bind_subject(face_228_390_8_235158, &sb_time_weekday);
    lv_obj_set_x(face_228_390_8_235158, 21);
    lv_obj_set_y(face_228_390_8_235158, 277);


#endif
    return face_228_390;
}

