
// File generated by bin2lvgl.py
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 228_390

#ifndef _FACE_228_390_H
#define _FACE_228_390_H

#ifdef __cplusplus
extern "C"
{
#endif

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
    #include "lvgl.h"
    #include "lvgl_private.h"
#else
    #include "lvgl/lvgl.h"
    #include "lvgl/lvgl_private.h"
#endif

#include "helios_ui/helios_ui.h"
#include "helios_ui/custom/watchfaces/watchface_manager.h"

#ifndef ENABLE_FACE_228_390
#define ENABLE_FACE_228_390
#endif

#ifdef ENABLE_FACE_228_390

LV_IMG_DECLARE(face_228_390_dial_img_0_692_0);
LV_IMG_DECLARE(face_228_390_dial_img_1_183246_0);
LV_IMG_DECLARE(face_228_390_dial_img_1_183246_1);
LV_IMG_DECLARE(face_228_390_dial_img_1_183246_2);
LV_IMG_DECLARE(face_228_390_dial_img_1_183246_3);
LV_IMG_DECLARE(face_228_390_dial_img_1_183246_4);
LV_IMG_DECLARE(face_228_390_dial_img_1_183246_5);
LV_IMG_DECLARE(face_228_390_dial_img_1_183246_6);
LV_IMG_DECLARE(face_228_390_dial_img_1_183246_7);
LV_IMG_DECLARE(face_228_390_dial_img_1_183246_8);
LV_IMG_DECLARE(face_228_390_dial_img_1_183246_9);
LV_IMG_DECLARE(face_228_390_dial_img_3_186360_0);
LV_IMG_DECLARE(face_228_390_dial_img_3_186360_1);
LV_IMG_DECLARE(face_228_390_dial_img_3_186360_2);
LV_IMG_DECLARE(face_228_390_dial_img_3_186360_3);
LV_IMG_DECLARE(face_228_390_dial_img_3_186360_4);
LV_IMG_DECLARE(face_228_390_dial_img_3_186360_5);
LV_IMG_DECLARE(face_228_390_dial_img_3_186360_6);
LV_IMG_DECLARE(face_228_390_dial_img_3_186360_7);
LV_IMG_DECLARE(face_228_390_dial_img_3_186360_8);
LV_IMG_DECLARE(face_228_390_dial_img_3_186360_9);
LV_IMG_DECLARE(face_228_390_dial_img_7_228194_6);
LV_IMG_DECLARE(face_228_390_dial_img_7_228194_0);
LV_IMG_DECLARE(face_228_390_dial_img_7_228194_1);
LV_IMG_DECLARE(face_228_390_dial_img_7_228194_2);
LV_IMG_DECLARE(face_228_390_dial_img_7_228194_3);
LV_IMG_DECLARE(face_228_390_dial_img_7_228194_4);
LV_IMG_DECLARE(face_228_390_dial_img_7_228194_5);
LV_IMG_DECLARE(face_228_390_dial_img_8_235158_6);
LV_IMG_DECLARE(face_228_390_dial_img_8_235158_0);
LV_IMG_DECLARE(face_228_390_dial_img_8_235158_1);
LV_IMG_DECLARE(face_228_390_dial_img_8_235158_2);
LV_IMG_DECLARE(face_228_390_dial_img_8_235158_3);
LV_IMG_DECLARE(face_228_390_dial_img_8_235158_4);
LV_IMG_DECLARE(face_228_390_dial_img_8_235158_5);
LV_IMG_DECLARE(face_228_390_dial_img_preview_0);
LV_IMG_DECLARE(face_228_390_dial_img_preview_0);


#endif

lv_obj_t *init_face_228_390(lv_obj_t *parent);
    

#ifdef __cplusplus
}
#endif

#endif
