
// File generated by bin2lvgl.py
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 1891_2_390

#include "1891_2_390.h"

#ifdef ENABLE_FACE_1891_2_390

static const void *face_1891_2_390_dial_img_weather[] = {
	&face_1891_2_390_dial_img_2_16140_0,
	&face_1891_2_390_dial_img_3_19338_0,
	&face_1891_2_390_dial_img_4_22758_0,
	&face_1891_2_390_dial_img_5_26050_0,
	&face_1891_2_390_dial_img_6_29318_0,
	&face_1891_2_390_dial_img_7_32682_0,
	&face_1891_2_390_dial_img_8_36034_0,
	&face_1891_2_390_dial_img_9_39454_0,
	&face_1891_2_390_dial_img_10_42716_0,
};
static const void *face_1891_2_390_dial_img_11_45662_group[] = {
	&face_1891_2_390_dial_img_11_45662_6,
	&face_1891_2_390_dial_img_11_45662_0,
	&face_1891_2_390_dial_img_11_45662_1,
	&face_1891_2_390_dial_img_11_45662_2,
	&face_1891_2_390_dial_img_11_45662_3,
	&face_1891_2_390_dial_img_11_45662_4,
	&face_1891_2_390_dial_img_11_45662_5,
};
static const void *face_1891_2_390_dial_img_12_56861_group[] = {
	&face_1891_2_390_dial_img_12_56861_6,
	&face_1891_2_390_dial_img_12_56861_0,
	&face_1891_2_390_dial_img_12_56861_1,
	&face_1891_2_390_dial_img_12_56861_2,
	&face_1891_2_390_dial_img_12_56861_3,
	&face_1891_2_390_dial_img_12_56861_4,
	&face_1891_2_390_dial_img_12_56861_5,
};
static const void *face_1891_2_390_dial_img_13_71714_group[] = {
	&face_1891_2_390_dial_img_13_71714_0,
	&face_1891_2_390_dial_img_13_71714_1,
	&face_1891_2_390_dial_img_13_71714_2,
	&face_1891_2_390_dial_img_13_71714_3,
	&face_1891_2_390_dial_img_13_71714_4,
	&face_1891_2_390_dial_img_13_71714_5,
	&face_1891_2_390_dial_img_13_71714_6,
	&face_1891_2_390_dial_img_13_71714_7,
	&face_1891_2_390_dial_img_13_71714_8,
	&face_1891_2_390_dial_img_13_71714_9,
};
static const void *face_1891_2_390_dial_img_15_296082_group[] = {
	&face_1891_2_390_dial_img_15_296082_0,
	&face_1891_2_390_dial_img_15_296082_1,
	&face_1891_2_390_dial_img_15_296082_2,
	&face_1891_2_390_dial_img_15_296082_3,
	&face_1891_2_390_dial_img_15_296082_4,
	&face_1891_2_390_dial_img_15_296082_5,
	&face_1891_2_390_dial_img_15_296082_6,
	&face_1891_2_390_dial_img_15_296082_7,
	&face_1891_2_390_dial_img_15_296082_8,
	&face_1891_2_390_dial_img_15_296082_9,
};
static const void *face_1891_2_390_dial_img_16_560264_group[] = {
	&face_1891_2_390_dial_img_16_560264_0,
	&face_1891_2_390_dial_img_16_560264_1,
	&face_1891_2_390_dial_img_16_560264_2,
	&face_1891_2_390_dial_img_16_560264_3,
	&face_1891_2_390_dial_img_16_560264_4,
	&face_1891_2_390_dial_img_16_560264_5,
	&face_1891_2_390_dial_img_16_560264_6,
	&face_1891_2_390_dial_img_16_560264_7,
	&face_1891_2_390_dial_img_16_560264_8,
	&face_1891_2_390_dial_img_16_560264_9,
};
static const void *face_1891_2_390_dial_img_17_823978_group[] = {
	&face_1891_2_390_dial_img_17_823978_0,
	&face_1891_2_390_dial_img_17_823978_1,
	&face_1891_2_390_dial_img_17_823978_2,
	&face_1891_2_390_dial_img_17_823978_3,
	&face_1891_2_390_dial_img_17_823978_4,
	&face_1891_2_390_dial_img_17_823978_5,
	&face_1891_2_390_dial_img_17_823978_6,
	&face_1891_2_390_dial_img_17_823978_7,
	&face_1891_2_390_dial_img_17_823978_8,
	&face_1891_2_390_dial_img_17_823978_9,
};




HELIOS_REGISTER_WATCHFACE(
    "1891",
    "1891_2_390",
    init_face_1891_2_390,
    &face_1891_2_390_dial_img_preview_0
);

#endif

lv_obj_t *init_face_1891_2_390(lv_obj_t *parent){
    lv_obj_t *face_1891_2_390 = lv_obj_create(parent);
#ifdef ENABLE_FACE_1891_2_390
    
    lv_obj_remove_style_all(face_1891_2_390);
    lv_obj_set_size(face_1891_2_390, lv_pct(100),lv_pct(100));
    lv_obj_set_flag(face_1891_2_390, LV_OBJ_FLAG_SCROLLABLE, false);
    lv_obj_set_flag(face_1891_2_390, LV_OBJ_FLAG_CLICKABLE, false);

    
    lv_obj_t *face_1891_2_390_0_1044 = lv_img_create(face_1891_2_390);
    lv_img_set_src(face_1891_2_390_0_1044, &face_1891_2_390_dial_img_0_1044_0);
    lv_obj_set_width(face_1891_2_390_0_1044, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1891_2_390_0_1044, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1891_2_390_0_1044, 263);
    lv_obj_set_y(face_1891_2_390_0_1044, 209);

    lv_obj_t *face_1891_2_390_2_16140 = wf_item_create(face_1891_2_390);
    wf_item_set_place_value(face_1891_2_390_2_16140, 0);
    wf_item_set_image_array(face_1891_2_390_2_16140, face_1891_2_390_dial_img_weather, 8);
    wf_item_bind_subject(face_1891_2_390_2_16140, &sb_weather_code);
    lv_obj_set_x(face_1891_2_390_2_16140, 295);
    lv_obj_set_y(face_1891_2_390_2_16140, 68);

    lv_obj_t *face_1891_2_390_12_56861 = wf_item_create(face_1891_2_390);
    wf_item_set_place_value(face_1891_2_390_12_56861, 0);
    wf_item_set_image_array(face_1891_2_390_12_56861, face_1891_2_390_dial_img_12_56861_group, 7);
    wf_item_bind_subject(face_1891_2_390_12_56861, &sb_time_weekday);
    lv_obj_set_x(face_1891_2_390_12_56861, 258);
    lv_obj_set_y(face_1891_2_390_12_56861, 375);

    lv_obj_t *face_1891_2_390_13_71714 = wf_item_create(face_1891_2_390);
    wf_item_set_place_value(face_1891_2_390_13_71714, 0);
    wf_item_set_image_array(face_1891_2_390_13_71714, face_1891_2_390_dial_img_13_71714_group, 10);
    wf_item_bind_subject(face_1891_2_390_13_71714, &sb_time_hour);
    lv_obj_set_x(face_1891_2_390_13_71714, 144);
    lv_obj_set_y(face_1891_2_390_13_71714, 34);

    lv_obj_t *face_1891_2_390_14_71714 = wf_item_create(face_1891_2_390);
    wf_item_set_place_value(face_1891_2_390_14_71714, 1);
    wf_item_set_image_array(face_1891_2_390_14_71714, face_1891_2_390_dial_img_13_71714_group, 10);
    wf_item_bind_subject(face_1891_2_390_14_71714, &sb_time_hour);
    lv_obj_set_x(face_1891_2_390_14_71714, 11);
    lv_obj_set_y(face_1891_2_390_14_71714, 34);

    lv_obj_t *face_1891_2_390_15_296082 = wf_item_create(face_1891_2_390);
    wf_item_set_place_value(face_1891_2_390_15_296082, 0);
    wf_item_set_image_array(face_1891_2_390_15_296082, face_1891_2_390_dial_img_15_296082_group, 10);
    wf_item_bind_subject(face_1891_2_390_15_296082, &sb_time_minute);
    lv_obj_set_x(face_1891_2_390_15_296082, 131);
    lv_obj_set_y(face_1891_2_390_15_296082, 245);

    lv_obj_t *face_1891_2_390_16_560264 = wf_item_create(face_1891_2_390);
    wf_item_set_place_value(face_1891_2_390_16_560264, 1);
    wf_item_set_image_array(face_1891_2_390_16_560264, face_1891_2_390_dial_img_16_560264_group, 10);
    wf_item_bind_subject(face_1891_2_390_16_560264, &sb_time_minute);
    lv_obj_set_x(face_1891_2_390_16_560264, 3);
    lv_obj_set_y(face_1891_2_390_16_560264, 245);

    lv_obj_t *face_1891_2_390_17_823978 = wf_item_create(face_1891_2_390);
    wf_item_set_place_value(face_1891_2_390_17_823978, 0);
    wf_item_set_image_array(face_1891_2_390_17_823978, face_1891_2_390_dial_img_17_823978_group, 10);
    wf_item_bind_subject(face_1891_2_390_17_823978, &sb_time_day);
    lv_obj_set_x(face_1891_2_390_17_823978, 357);
    lv_obj_set_y(face_1891_2_390_17_823978, 375);

    lv_obj_t *face_1891_2_390_18_823978 = wf_item_create(face_1891_2_390);
    wf_item_set_place_value(face_1891_2_390_18_823978, 1);
    wf_item_set_image_array(face_1891_2_390_18_823978, face_1891_2_390_dial_img_17_823978_group, 10);
    wf_item_bind_subject(face_1891_2_390_18_823978, &sb_time_day);
    lv_obj_set_x(face_1891_2_390_18_823978, 339);
    lv_obj_set_y(face_1891_2_390_18_823978, 375);

    lv_obj_t *face_1891_2_390_19_823978 = wf_item_create(face_1891_2_390);
    wf_item_set_place_value(face_1891_2_390_19_823978, 0);
    wf_item_set_image_array(face_1891_2_390_19_823978, face_1891_2_390_dial_img_17_823978_group, 10);
    wf_item_bind_subject(face_1891_2_390_19_823978, &sb_health_bpm);
    lv_obj_set_x(face_1891_2_390_19_823978, 331);
    lv_obj_set_y(face_1891_2_390_19_823978, 251);

    lv_obj_t *face_1891_2_390_20_823978 = wf_item_create(face_1891_2_390);
    wf_item_set_place_value(face_1891_2_390_20_823978, 1);
    wf_item_set_image_array(face_1891_2_390_20_823978, face_1891_2_390_dial_img_17_823978_group, 10);
    wf_item_bind_subject(face_1891_2_390_20_823978, &sb_health_bpm);
    lv_obj_set_x(face_1891_2_390_20_823978, 313);
    lv_obj_set_y(face_1891_2_390_20_823978, 251);

    lv_obj_t *face_1891_2_390_21_823978 = wf_item_create(face_1891_2_390);
    wf_item_set_place_value(face_1891_2_390_21_823978, 2);
    wf_item_set_image_array(face_1891_2_390_21_823978, face_1891_2_390_dial_img_17_823978_group, 10);
    wf_item_bind_subject(face_1891_2_390_21_823978, &sb_health_bpm);
    lv_obj_set_x(face_1891_2_390_21_823978, 295);
    lv_obj_set_y(face_1891_2_390_21_823978, 251);

    lv_obj_t *face_1891_2_390_22_0 = lv_img_create(face_1891_2_390);
    lv_img_set_src(face_1891_2_390_22_0, &face_1891_2_390_dial_img_22_0_0);
    lv_obj_set_width(face_1891_2_390_22_0, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1891_2_390_22_0, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1891_2_390_22_0, 320);
    lv_obj_set_y(face_1891_2_390_22_0, 143);

    lv_obj_t *face_1891_2_390_23_0 = lv_img_create(face_1891_2_390);
    lv_img_set_src(face_1891_2_390_23_0, &face_1891_2_390_dial_img_22_0_0);
    lv_obj_set_width(face_1891_2_390_23_0, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1891_2_390_23_0, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1891_2_390_23_0, 302);
    lv_obj_set_y(face_1891_2_390_23_0, 143);

    lv_obj_t *face_1891_2_390_24_823978 = lv_img_create(face_1891_2_390);
    lv_img_set_src(face_1891_2_390_24_823978, &face_1891_2_390_dial_img_17_823978_0);
    lv_obj_set_width(face_1891_2_390_24_823978, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1891_2_390_24_823978, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1891_2_390_24_823978, 320);
    lv_obj_set_y(face_1891_2_390_24_823978, 130);

    lv_obj_t *face_1891_2_390_25_823978 = lv_img_create(face_1891_2_390);
    lv_img_set_src(face_1891_2_390_25_823978, &face_1891_2_390_dial_img_17_823978_0);
    lv_obj_set_width(face_1891_2_390_25_823978, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1891_2_390_25_823978, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1891_2_390_25_823978, 302);
    lv_obj_set_y(face_1891_2_390_25_823978, 130);

    lv_obj_t *face_1891_2_390_26_823978 = lv_img_create(face_1891_2_390);
    lv_img_set_src(face_1891_2_390_26_823978, &face_1891_2_390_dial_img_17_823978_0);
    lv_obj_set_width(face_1891_2_390_26_823978, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1891_2_390_26_823978, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1891_2_390_26_823978, 302);
    lv_obj_set_y(face_1891_2_390_26_823978, 130);

    lv_obj_t *face_1891_2_390_27_828940 = lv_img_create(face_1891_2_390);
    lv_img_set_src(face_1891_2_390_27_828940, &face_1891_2_390_dial_img_27_828940_0);
    lv_obj_set_width(face_1891_2_390_27_828940, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1891_2_390_27_828940, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1891_2_390_27_828940, 344);
    lv_obj_set_y(face_1891_2_390_27_828940, 130);

    lv_obj_t *face_1891_2_390_28_829778 = lv_img_create(face_1891_2_390);
    lv_img_set_src(face_1891_2_390_28_829778, &face_1891_2_390_dial_img_28_829778_0);
    lv_obj_set_width(face_1891_2_390_28_829778, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1891_2_390_28_829778, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1891_2_390_28_829778, 344);
    lv_obj_set_y(face_1891_2_390_28_829778, 130);

    lv_obj_t *face_1891_2_390_29_0 = lv_img_create(face_1891_2_390);
    lv_img_set_src(face_1891_2_390_29_0, &face_1891_2_390_dial_img_22_0_0);
    lv_obj_set_width(face_1891_2_390_29_0, LV_SIZE_CONTENT);
    lv_obj_set_height(face_1891_2_390_29_0, LV_SIZE_CONTENT);
    lv_obj_set_x(face_1891_2_390_29_0, 289);
    lv_obj_set_y(face_1891_2_390_29_0, 143);


#endif
    return face_1891_2_390;
}

