
// File generated by bin2lvgl.py
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 1891_2_390

#ifndef _FACE_1891_2_390_H
#define _FACE_1891_2_390_H

#ifdef __cplusplus
extern "C"
{
#endif

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
    #include "lvgl.h"
    #include "lvgl_private.h"
#else
    #include "lvgl/lvgl.h"
    #include "lvgl/lvgl_private.h"
#endif

#include "helios_ui/helios_ui.h"
#include "helios_ui/custom/watchfaces/watchface_manager.h"

#ifndef ENABLE_FACE_1891_2_390
#define ENABLE_FACE_1891_2_390
#endif

#ifdef ENABLE_FACE_1891_2_390

LV_IMG_DECLARE(face_1891_2_390_dial_img_0_1044_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_2_16140_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_3_19338_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_4_22758_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_5_26050_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_6_29318_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_7_32682_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_8_36034_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_9_39454_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_10_42716_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_11_45662_6);
LV_IMG_DECLARE(face_1891_2_390_dial_img_11_45662_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_11_45662_1);
LV_IMG_DECLARE(face_1891_2_390_dial_img_11_45662_2);
LV_IMG_DECLARE(face_1891_2_390_dial_img_11_45662_3);
LV_IMG_DECLARE(face_1891_2_390_dial_img_11_45662_4);
LV_IMG_DECLARE(face_1891_2_390_dial_img_11_45662_5);
LV_IMG_DECLARE(face_1891_2_390_dial_img_12_56861_6);
LV_IMG_DECLARE(face_1891_2_390_dial_img_12_56861_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_12_56861_1);
LV_IMG_DECLARE(face_1891_2_390_dial_img_12_56861_2);
LV_IMG_DECLARE(face_1891_2_390_dial_img_12_56861_3);
LV_IMG_DECLARE(face_1891_2_390_dial_img_12_56861_4);
LV_IMG_DECLARE(face_1891_2_390_dial_img_12_56861_5);
LV_IMG_DECLARE(face_1891_2_390_dial_img_13_71714_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_13_71714_1);
LV_IMG_DECLARE(face_1891_2_390_dial_img_13_71714_2);
LV_IMG_DECLARE(face_1891_2_390_dial_img_13_71714_3);
LV_IMG_DECLARE(face_1891_2_390_dial_img_13_71714_4);
LV_IMG_DECLARE(face_1891_2_390_dial_img_13_71714_5);
LV_IMG_DECLARE(face_1891_2_390_dial_img_13_71714_6);
LV_IMG_DECLARE(face_1891_2_390_dial_img_13_71714_7);
LV_IMG_DECLARE(face_1891_2_390_dial_img_13_71714_8);
LV_IMG_DECLARE(face_1891_2_390_dial_img_13_71714_9);
LV_IMG_DECLARE(face_1891_2_390_dial_img_15_296082_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_15_296082_1);
LV_IMG_DECLARE(face_1891_2_390_dial_img_15_296082_2);
LV_IMG_DECLARE(face_1891_2_390_dial_img_15_296082_3);
LV_IMG_DECLARE(face_1891_2_390_dial_img_15_296082_4);
LV_IMG_DECLARE(face_1891_2_390_dial_img_15_296082_5);
LV_IMG_DECLARE(face_1891_2_390_dial_img_15_296082_6);
LV_IMG_DECLARE(face_1891_2_390_dial_img_15_296082_7);
LV_IMG_DECLARE(face_1891_2_390_dial_img_15_296082_8);
LV_IMG_DECLARE(face_1891_2_390_dial_img_15_296082_9);
LV_IMG_DECLARE(face_1891_2_390_dial_img_16_560264_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_16_560264_1);
LV_IMG_DECLARE(face_1891_2_390_dial_img_16_560264_2);
LV_IMG_DECLARE(face_1891_2_390_dial_img_16_560264_3);
LV_IMG_DECLARE(face_1891_2_390_dial_img_16_560264_4);
LV_IMG_DECLARE(face_1891_2_390_dial_img_16_560264_5);
LV_IMG_DECLARE(face_1891_2_390_dial_img_16_560264_6);
LV_IMG_DECLARE(face_1891_2_390_dial_img_16_560264_7);
LV_IMG_DECLARE(face_1891_2_390_dial_img_16_560264_8);
LV_IMG_DECLARE(face_1891_2_390_dial_img_16_560264_9);
LV_IMG_DECLARE(face_1891_2_390_dial_img_17_823978_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_17_823978_1);
LV_IMG_DECLARE(face_1891_2_390_dial_img_17_823978_2);
LV_IMG_DECLARE(face_1891_2_390_dial_img_17_823978_3);
LV_IMG_DECLARE(face_1891_2_390_dial_img_17_823978_4);
LV_IMG_DECLARE(face_1891_2_390_dial_img_17_823978_5);
LV_IMG_DECLARE(face_1891_2_390_dial_img_17_823978_6);
LV_IMG_DECLARE(face_1891_2_390_dial_img_17_823978_7);
LV_IMG_DECLARE(face_1891_2_390_dial_img_17_823978_8);
LV_IMG_DECLARE(face_1891_2_390_dial_img_17_823978_9);
LV_IMG_DECLARE(face_1891_2_390_dial_img_22_0_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_27_828940_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_28_829778_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_preview_0);
LV_IMG_DECLARE(face_1891_2_390_dial_img_preview_0);


#endif

lv_obj_t *init_face_1891_2_390(lv_obj_t *parent);
    

#ifdef __cplusplus
}
#endif

#endif
