
// File generated by bin2lvgl.py
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 174_390

#include "174_390.h"

#ifdef ENABLE_FACE_174_390

static const void *face_174_390_dial_img_7_51169_ampm_group[] = {
	&face_174_390_dial_img_6_49679_0,
	&face_174_390_dial_img_7_51169_0,
};
static const void *face_174_390_dial_img_14_58553_group[] = {
	&face_174_390_dial_img_14_58553_0,
	&face_174_390_dial_img_14_58553_1,
	&face_174_390_dial_img_14_58553_2,
	&face_174_390_dial_img_14_58553_3,
	&face_174_390_dial_img_14_58553_4,
	&face_174_390_dial_img_14_58553_5,
	&face_174_390_dial_img_14_58553_6,
	&face_174_390_dial_img_14_58553_7,
	&face_174_390_dial_img_14_58553_8,
	&face_174_390_dial_img_14_58553_9,
};
static const void *face_174_390_dial_img_26_61527_group[] = {
	&face_174_390_dial_img_26_61527_0,
	&face_174_390_dial_img_26_61527_1,
	&face_174_390_dial_img_26_61527_2,
	&face_174_390_dial_img_26_61527_3,
	&face_174_390_dial_img_26_61527_4,
	&face_174_390_dial_img_26_61527_5,
	&face_174_390_dial_img_26_61527_6,
	&face_174_390_dial_img_26_61527_7,
	&face_174_390_dial_img_26_61527_8,
	&face_174_390_dial_img_26_61527_9,
};
static const void *face_174_390_dial_img_31_67647_group[] = {
	&face_174_390_dial_img_31_67647_0,
	&face_174_390_dial_img_31_67647_1,
	&face_174_390_dial_img_31_67647_2,
	&face_174_390_dial_img_31_67647_3,
	&face_174_390_dial_img_31_67647_4,
	&face_174_390_dial_img_31_67647_5,
	&face_174_390_dial_img_31_67647_6,
	&face_174_390_dial_img_31_67647_7,
	&face_174_390_dial_img_31_67647_8,
	&face_174_390_dial_img_31_67647_9,
};
static const void *face_174_390_dial_img_33_171137_group[] = {
	&face_174_390_dial_img_33_171137_0,
	&face_174_390_dial_img_33_171137_1,
	&face_174_390_dial_img_33_171137_2,
	&face_174_390_dial_img_33_171137_3,
	&face_174_390_dial_img_33_171137_4,
	&face_174_390_dial_img_33_171137_5,
	&face_174_390_dial_img_33_171137_6,
	&face_174_390_dial_img_33_171137_7,
	&face_174_390_dial_img_33_171137_8,
	&face_174_390_dial_img_33_171137_9,
};
static const void *face_174_390_dial_img_35_303091_group[] = {
	&face_174_390_dial_img_35_303091_6,
	&face_174_390_dial_img_35_303091_0,
	&face_174_390_dial_img_35_303091_1,
	&face_174_390_dial_img_35_303091_2,
	&face_174_390_dial_img_35_303091_3,
	&face_174_390_dial_img_35_303091_4,
	&face_174_390_dial_img_35_303091_5,
};
static const void *face_174_390_dial_img_36_320023_group[] = {
	&face_174_390_dial_img_36_320023_6,
	&face_174_390_dial_img_36_320023_0,
	&face_174_390_dial_img_36_320023_1,
	&face_174_390_dial_img_36_320023_2,
	&face_174_390_dial_img_36_320023_3,
	&face_174_390_dial_img_36_320023_4,
	&face_174_390_dial_img_36_320023_5,
};




HELIOS_REGISTER_WATCHFACE(
    "174",
    "174_390",
    init_face_174_390,
    &face_174_390_dial_img_preview_0
);

#endif

lv_obj_t *init_face_174_390(lv_obj_t *parent){
    lv_obj_t *face_174_390 = lv_obj_create(parent);
#ifdef ENABLE_FACE_174_390
    
    lv_obj_remove_style_all(face_174_390);
    lv_obj_set_size(face_174_390, lv_pct(100), lv_pct(100));
    lv_obj_set_flag(face_174_390, LV_OBJ_FLAG_SCROLLABLE, false);
    lv_obj_set_flag(face_174_390, LV_OBJ_FLAG_CLICKABLE, false);

    
    lv_obj_t *face_174_390_0_1122 = lv_img_create(face_174_390);
    lv_img_set_src(face_174_390_0_1122, &face_174_390_dial_img_0_1122_0);
    lv_obj_set_width(face_174_390_0_1122, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_390_0_1122, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_390_0_1122, 17);
    lv_obj_set_y(face_174_390_0_1122, 152);

    lv_obj_t *face_174_390_1_8091 = lv_img_create(face_174_390);
    lv_img_set_src(face_174_390_1_8091, &face_174_390_dial_img_1_8091_0);
    lv_obj_set_width(face_174_390_1_8091, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_390_1_8091, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_390_1_8091, 17);
    lv_obj_set_y(face_174_390_1_8091, 266);

    lv_obj_t *face_174_390_2_14680 = lv_img_create(face_174_390);
    lv_img_set_src(face_174_390_2_14680, &face_174_390_dial_img_2_14680_0);
    lv_obj_set_width(face_174_390_2_14680, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_390_2_14680, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_390_2_14680, 17);
    lv_obj_set_y(face_174_390_2_14680, 375);

    lv_obj_t *face_174_390_3_38328 = lv_img_create(face_174_390);
    lv_img_set_src(face_174_390_3_38328, &face_174_390_dial_img_3_38328_0);
    lv_obj_set_width(face_174_390_3_38328, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_390_3_38328, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_390_3_38328, 17);
    lv_obj_set_y(face_174_390_3_38328, 40);

    lv_obj_t *face_174_390_7_51169 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_7_51169, 0);
    wf_item_set_image_array(face_174_390_7_51169, face_174_390_dial_img_7_51169_ampm_group, 2);
    wf_item_bind_subject(face_174_390_7_51169, &sb_time_am);
    lv_obj_set_x(face_174_390_7_51169, 152);
    lv_obj_set_y(face_174_390_7_51169, 399);

    lv_obj_t *face_174_390_9_53825 = lv_img_create(face_174_390);
    lv_img_set_src(face_174_390_9_53825, &face_174_390_dial_img_9_53825_0);
    lv_obj_set_width(face_174_390_9_53825, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_390_9_53825, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_390_9_53825, 128);
    lv_obj_set_y(face_174_390_9_53825, 58);

    lv_obj_t *face_174_390_11_55525 = lv_img_create(face_174_390);
    lv_img_set_src(face_174_390_11_55525, &face_174_390_dial_img_11_55525_0);
    lv_obj_set_width(face_174_390_11_55525, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_390_11_55525, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_390_11_55525, 121);
    lv_obj_set_y(face_174_390_11_55525, 277);

    lv_obj_t *face_174_390_13_57463 = lv_img_create(face_174_390);
    lv_img_set_src(face_174_390_13_57463, &face_174_390_dial_img_13_57463_0);
    lv_obj_set_width(face_174_390_13_57463, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_390_13_57463, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_390_13_57463, 117);
    lv_obj_set_y(face_174_390_13_57463, 177);

    lv_obj_t *face_174_390_14_58553 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_14_58553, 0);
    wf_item_set_image_array(face_174_390_14_58553, face_174_390_dial_img_14_58553_group, 10);
    wf_item_bind_subject(face_174_390_14_58553, &sb_health_bpm);
    lv_obj_set_x(face_174_390_14_58553, 157);
    lv_obj_set_y(face_174_390_14_58553, 91);

    lv_obj_t *face_174_390_15_58553 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_15_58553, 1);
    wf_item_set_image_array(face_174_390_15_58553, face_174_390_dial_img_14_58553_group, 10);
    wf_item_bind_subject(face_174_390_15_58553, &sb_health_bpm);
    lv_obj_set_x(face_174_390_15_58553, 143);
    lv_obj_set_y(face_174_390_15_58553, 91);

    lv_obj_t *face_174_390_16_58553 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_16_58553, 2);
    wf_item_set_image_array(face_174_390_16_58553, face_174_390_dial_img_14_58553_group, 10);
    wf_item_bind_subject(face_174_390_16_58553, &sb_health_bpm);
    lv_obj_set_x(face_174_390_16_58553, 128);
    lv_obj_set_y(face_174_390_16_58553, 91);

    lv_obj_t *face_174_390_17_58553 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_17_58553, 0);
    wf_item_set_image_array(face_174_390_17_58553, face_174_390_dial_img_14_58553_group, 10);
    wf_item_bind_subject(face_174_390_17_58553, &sb_activity_kcal);
    lv_obj_set_x(face_174_390_17_58553, 164);
    lv_obj_set_y(face_174_390_17_58553, 310);

    lv_obj_t *face_174_390_18_58553 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_18_58553, 1);
    wf_item_set_image_array(face_174_390_18_58553, face_174_390_dial_img_14_58553_group, 10);
    wf_item_bind_subject(face_174_390_18_58553, &sb_activity_kcal);
    lv_obj_set_x(face_174_390_18_58553, 149);
    lv_obj_set_y(face_174_390_18_58553, 310);

    lv_obj_t *face_174_390_19_58553 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_19_58553, 2);
    wf_item_set_image_array(face_174_390_19_58553, face_174_390_dial_img_14_58553_group, 10);
    wf_item_bind_subject(face_174_390_19_58553, &sb_activity_kcal);
    lv_obj_set_x(face_174_390_19_58553, 134);
    lv_obj_set_y(face_174_390_19_58553, 310);

    lv_obj_t *face_174_390_20_58553 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_20_58553, 3);
    wf_item_set_image_array(face_174_390_20_58553, face_174_390_dial_img_14_58553_group, 10);
    wf_item_bind_subject(face_174_390_20_58553, &sb_activity_kcal);
    lv_obj_set_x(face_174_390_20_58553, 120);
    lv_obj_set_y(face_174_390_20_58553, 310);

    lv_obj_t *face_174_390_21_58553 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_21_58553, 0);
    wf_item_set_image_array(face_174_390_21_58553, face_174_390_dial_img_14_58553_group, 10);
    wf_item_bind_subject(face_174_390_21_58553, &sb_activity_steps);
    lv_obj_set_x(face_174_390_21_58553, 172);
    lv_obj_set_y(face_174_390_21_58553, 208);

    lv_obj_t *face_174_390_22_58553 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_22_58553, 1);
    wf_item_set_image_array(face_174_390_22_58553, face_174_390_dial_img_14_58553_group, 10);
    wf_item_bind_subject(face_174_390_22_58553, &sb_activity_steps);
    lv_obj_set_x(face_174_390_22_58553, 157);
    lv_obj_set_y(face_174_390_22_58553, 208);

    lv_obj_t *face_174_390_23_58553 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_23_58553, 2);
    wf_item_set_image_array(face_174_390_23_58553, face_174_390_dial_img_14_58553_group, 10);
    wf_item_bind_subject(face_174_390_23_58553, &sb_activity_steps);
    lv_obj_set_x(face_174_390_23_58553, 143);
    lv_obj_set_y(face_174_390_23_58553, 208);

    lv_obj_t *face_174_390_24_58553 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_24_58553, 3);
    wf_item_set_image_array(face_174_390_24_58553, face_174_390_dial_img_14_58553_group, 10);
    wf_item_bind_subject(face_174_390_24_58553, &sb_activity_steps);
    lv_obj_set_x(face_174_390_24_58553, 128);
    lv_obj_set_y(face_174_390_24_58553, 208);

    lv_obj_t *face_174_390_25_58553 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_25_58553, 4);
    wf_item_set_image_array(face_174_390_25_58553, face_174_390_dial_img_14_58553_group, 10);
    wf_item_bind_subject(face_174_390_25_58553, &sb_activity_steps);
    lv_obj_set_x(face_174_390_25_58553, 113);
    lv_obj_set_y(face_174_390_25_58553, 208);

    lv_obj_t *face_174_390_26_61527 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_26_61527, 0);
    wf_item_set_image_array(face_174_390_26_61527, face_174_390_dial_img_26_61527_group, 10);
    wf_item_bind_subject(face_174_390_26_61527, &sb_time_month);
    lv_obj_set_x(face_174_390_26_61527, 256);
    lv_obj_set_y(face_174_390_26_61527, 396);

    lv_obj_t *face_174_390_27_61527 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_27_61527, 1);
    wf_item_set_image_array(face_174_390_27_61527, face_174_390_dial_img_26_61527_group, 10);
    wf_item_bind_subject(face_174_390_27_61527, &sb_time_month);
    lv_obj_set_x(face_174_390_27_61527, 237);
    lv_obj_set_y(face_174_390_27_61527, 396);

    lv_obj_t *face_174_390_28_67069 = lv_img_create(face_174_390);
    lv_img_set_src(face_174_390_28_67069, &face_174_390_dial_img_28_67069_0);
    lv_obj_set_width(face_174_390_28_67069, LV_SIZE_CONTENT);
    lv_obj_set_height(face_174_390_28_67069, LV_SIZE_CONTENT);
    lv_obj_set_x(face_174_390_28_67069, 276);
    lv_obj_set_y(face_174_390_28_67069, 394);

    lv_obj_t *face_174_390_29_61527 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_29_61527, 0);
    wf_item_set_image_array(face_174_390_29_61527, face_174_390_dial_img_26_61527_group, 10);
    wf_item_bind_subject(face_174_390_29_61527, &sb_time_day);
    lv_obj_set_x(face_174_390_29_61527, 312);
    lv_obj_set_y(face_174_390_29_61527, 396);

    lv_obj_t *face_174_390_30_61527 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_30_61527, 1);
    wf_item_set_image_array(face_174_390_30_61527, face_174_390_dial_img_26_61527_group, 10);
    wf_item_bind_subject(face_174_390_30_61527, &sb_time_day);
    lv_obj_set_x(face_174_390_30_61527, 292);
    lv_obj_set_y(face_174_390_30_61527, 396);

    lv_obj_t *face_174_390_31_67647 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_31_67647, 0);
    wf_item_set_image_array(face_174_390_31_67647, face_174_390_dial_img_31_67647_group, 10);
    wf_item_bind_subject(face_174_390_31_67647, &sb_time_hour);
    lv_obj_set_x(face_174_390_31_67647, 289);
    lv_obj_set_y(face_174_390_31_67647, 43);

    lv_obj_t *face_174_390_32_67647 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_32_67647, 1);
    wf_item_set_image_array(face_174_390_32_67647, face_174_390_dial_img_31_67647_group, 10);
    wf_item_bind_subject(face_174_390_32_67647, &sb_time_hour);
    lv_obj_set_x(face_174_390_32_67647, 204);
    lv_obj_set_y(face_174_390_32_67647, 43);

    lv_obj_t *face_174_390_33_171137 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_33_171137, 0);
    wf_item_set_image_array(face_174_390_33_171137, face_174_390_dial_img_33_171137_group, 10);
    wf_item_bind_subject(face_174_390_33_171137, &sb_time_minute);
    lv_obj_set_x(face_174_390_33_171137, 286);
    lv_obj_set_y(face_174_390_33_171137, 211);

    lv_obj_t *face_174_390_34_171137 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_34_171137, 1);
    wf_item_set_image_array(face_174_390_34_171137, face_174_390_dial_img_33_171137_group, 10);
    wf_item_bind_subject(face_174_390_34_171137, &sb_time_minute);
    lv_obj_set_x(face_174_390_34_171137, 188);
    lv_obj_set_y(face_174_390_34_171137, 211);

    lv_obj_t *face_174_390_36_320023 = wf_item_create(face_174_390);
    wf_item_set_place_value(face_174_390_36_320023, 0);
    wf_item_set_image_array(face_174_390_36_320023, face_174_390_dial_img_36_320023_group, 7);
    wf_item_bind_subject(face_174_390_36_320023, &sb_time_weekday);
    lv_obj_set_x(face_174_390_36_320023, 50);
    lv_obj_set_y(face_174_390_36_320023, 398);


#endif
    return face_174_390;
}
