
// File generated by bin2lvgl.py
// developed by fbiego. 
// https://github.com/fbiego
// Watchface: 174_390

#ifndef _FACE_174_390_H
#define _FACE_174_390_H

#ifdef __cplusplus
extern "C"
{
#endif

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
    #include "lvgl.h"
    #include "lvgl_private.h"
#else
    #include "lvgl/lvgl.h"
    #include "lvgl/lvgl_private.h"
#endif

#include "helios_ui/helios_ui.h"
#include "helios_ui/custom/watchfaces/watchface_manager.h"

//#define ENABLE_FACE_174_390 // (174 390) uncomment to enable or define it elsewhere

#ifdef ENABLE_FACE_174_390

LV_IMG_DECLARE(face_174_390_dial_img_0_1122_0);
LV_IMG_DECLARE(face_174_390_dial_img_1_8091_0);
LV_IMG_DECLARE(face_174_390_dial_img_2_14680_0);
LV_IMG_DECLARE(face_174_390_dial_img_3_38328_0);
LV_IMG_DECLARE(face_174_390_dial_img_6_49679_0);
LV_IMG_DECLARE(face_174_390_dial_img_7_51169_0);
LV_IMG_DECLARE(face_174_390_dial_img_8_52581_0);
LV_IMG_DECLARE(face_174_390_dial_img_9_53825_0);
LV_IMG_DECLARE(face_174_390_dial_img_10_54545_0);
LV_IMG_DECLARE(face_174_390_dial_img_11_55525_0);
LV_IMG_DECLARE(face_174_390_dial_img_12_56439_0);
LV_IMG_DECLARE(face_174_390_dial_img_13_57463_0);
LV_IMG_DECLARE(face_174_390_dial_img_14_58553_0);
LV_IMG_DECLARE(face_174_390_dial_img_14_58553_1);
LV_IMG_DECLARE(face_174_390_dial_img_14_58553_2);
LV_IMG_DECLARE(face_174_390_dial_img_14_58553_3);
LV_IMG_DECLARE(face_174_390_dial_img_14_58553_4);
LV_IMG_DECLARE(face_174_390_dial_img_14_58553_5);
LV_IMG_DECLARE(face_174_390_dial_img_14_58553_6);
LV_IMG_DECLARE(face_174_390_dial_img_14_58553_7);
LV_IMG_DECLARE(face_174_390_dial_img_14_58553_8);
LV_IMG_DECLARE(face_174_390_dial_img_14_58553_9);
LV_IMG_DECLARE(face_174_390_dial_img_26_61527_0);
LV_IMG_DECLARE(face_174_390_dial_img_26_61527_1);
LV_IMG_DECLARE(face_174_390_dial_img_26_61527_2);
LV_IMG_DECLARE(face_174_390_dial_img_26_61527_3);
LV_IMG_DECLARE(face_174_390_dial_img_26_61527_4);
LV_IMG_DECLARE(face_174_390_dial_img_26_61527_5);
LV_IMG_DECLARE(face_174_390_dial_img_26_61527_6);
LV_IMG_DECLARE(face_174_390_dial_img_26_61527_7);
LV_IMG_DECLARE(face_174_390_dial_img_26_61527_8);
LV_IMG_DECLARE(face_174_390_dial_img_26_61527_9);
LV_IMG_DECLARE(face_174_390_dial_img_28_67069_0);
LV_IMG_DECLARE(face_174_390_dial_img_31_67647_0);
LV_IMG_DECLARE(face_174_390_dial_img_31_67647_1);
LV_IMG_DECLARE(face_174_390_dial_img_31_67647_2);
LV_IMG_DECLARE(face_174_390_dial_img_31_67647_3);
LV_IMG_DECLARE(face_174_390_dial_img_31_67647_4);
LV_IMG_DECLARE(face_174_390_dial_img_31_67647_5);
LV_IMG_DECLARE(face_174_390_dial_img_31_67647_6);
LV_IMG_DECLARE(face_174_390_dial_img_31_67647_7);
LV_IMG_DECLARE(face_174_390_dial_img_31_67647_8);
LV_IMG_DECLARE(face_174_390_dial_img_31_67647_9);
LV_IMG_DECLARE(face_174_390_dial_img_33_171137_0);
LV_IMG_DECLARE(face_174_390_dial_img_33_171137_1);
LV_IMG_DECLARE(face_174_390_dial_img_33_171137_2);
LV_IMG_DECLARE(face_174_390_dial_img_33_171137_3);
LV_IMG_DECLARE(face_174_390_dial_img_33_171137_4);
LV_IMG_DECLARE(face_174_390_dial_img_33_171137_5);
LV_IMG_DECLARE(face_174_390_dial_img_33_171137_6);
LV_IMG_DECLARE(face_174_390_dial_img_33_171137_7);
LV_IMG_DECLARE(face_174_390_dial_img_33_171137_8);
LV_IMG_DECLARE(face_174_390_dial_img_33_171137_9);
LV_IMG_DECLARE(face_174_390_dial_img_35_303091_6);
LV_IMG_DECLARE(face_174_390_dial_img_35_303091_0);
LV_IMG_DECLARE(face_174_390_dial_img_35_303091_1);
LV_IMG_DECLARE(face_174_390_dial_img_35_303091_2);
LV_IMG_DECLARE(face_174_390_dial_img_35_303091_3);
LV_IMG_DECLARE(face_174_390_dial_img_35_303091_4);
LV_IMG_DECLARE(face_174_390_dial_img_35_303091_5);
LV_IMG_DECLARE(face_174_390_dial_img_36_320023_6);
LV_IMG_DECLARE(face_174_390_dial_img_36_320023_0);
LV_IMG_DECLARE(face_174_390_dial_img_36_320023_1);
LV_IMG_DECLARE(face_174_390_dial_img_36_320023_2);
LV_IMG_DECLARE(face_174_390_dial_img_36_320023_3);
LV_IMG_DECLARE(face_174_390_dial_img_36_320023_4);
LV_IMG_DECLARE(face_174_390_dial_img_36_320023_5);
LV_IMG_DECLARE(face_174_390_dial_img_preview_0);
LV_IMG_DECLARE(face_174_390_dial_img_preview_0);


#endif

lv_obj_t *init_face_174_390(lv_obj_t *parent);
    

#ifdef __cplusplus
}
#endif

#endif
